In [1]:
import numpy as np
import pandas as pd

from pathlib import Path

import browse_dlg

import matplotlib.pyplot as plt
import mplcursors

import seaborn as sns

# from matplotlib import rc
# import matplotlib.pylab as plt

# rc('font', **{'family': 'serif', 'serif': ['Computer Modern']})
# rc('text', usetex=True)

%matplotlib widget

In [6]:
def load_preceding_experiments(root='.'):
    dfs_list = []
    preceding_experiments_collected = []
    while restore_filepath := browse_dlg.gui_fname(root):
        preceding_experiments_collected.append(restore_filepath.decode())
    for filepath in preceding_experiments_collected:
        df = pd.read_csv(Path(filepath), index_col='trial_index')
        dfs_list.append(df)
        
    print(preceding_experiments_collected)
    total_df = pd.concat(dfs_list, ignore_index=True)
    return total_df

# Load Experiment #

In [7]:
exp_root = Path(r'..\.out\experiments')
exp_data_df = load_preceding_experiments(exp_root)
exp_data_df

,gap_elpd,gap_pos_tr_val_elpd,arm_name_x,kappa_sqrt,num_states,arm_name_y,gap_pos_tr_val_elpd_mean,gap_pos_tr_val_elpd_sem,arm_name,gap_elpd_mean,gap_elpd_sem
0,2.601105,1.285358,0_0,27.676788,5,0_0,1.285358,0.951197,0_0,2.601105,3.105419
1,2.471811,1.464173,1_0,84.865662,5,1_0,1.464173,1.225219,1_0,2.471811,3.216573
2,2.988411,1.422505,2_0,67.565112,5,2_0,1.422505,1.164564,2_0,2.988411,3.906208
3,3.433741,1.358964,3_0,20.087751,5,3_0,1.358964,1.021557,3_0,3.433741,4.077108
4,3.967931,1.626685,4_0,1.849244,5,4_0,1.626685,1.094744,4_0,3.967931,4.611073
...,...,...,...,...,...,...,...,...,...,...,...
65,2.230660,1.355375,20_0,733.489369,3,20_0,1.355375,1.035434,20_0,2.230660,3.268442
66,1.250546,1.099933,21_0,457.498217,3,21_0,1.099933,0.855776,21_0,1.250546,1.703255
67,1.754848,1.132539,6_0,1000.000000,3,6_0,1.132539,0.762741,6_0,1.754848,2.551910
68,2.242182,0.876963,23_0,736.551650,3,23_0,0.876963,0.488760,23_0,2.242182,2.762417
69,1.351296,0.875932,24_0,476.209409,3,24_0,0.875932,0.567741,24_0,1.351296,1.376860

In [4]:
exp_data_df['kappa'] = exp_data_df['kappa_sqrt']**2
# exp_data_df['kappa_sqrt'] = np.sqrt(exp_data_df['kappa'])
# exp_data_df.sort_values('num_states')

In [5]:
from matplotlib import colors
my_cmap = sns.color_palette("rocket", as_cmap=True)
# my_cmap = sns.color_palette("coolwarm", as_cmap=True)
# my_cmap = plt.get_cmap('hot')
# sns.scatterplot(
#     data=exp_data_df, x="gap_elpd", y="gap_pos_tr_val_elpd", size=2, c=exp_data_df['kappa_sqrt'], cmap=my_cmap,
#     legend="full"
# )
# sns.set_context('paper')
# sns.set_style('whitegrid')

sc = exp_data_df.plot.scatter('gap_elpd', 'gap_pos_tr_val_elpd', s=30, c='kappa_sqrt', cmap=my_cmap, norm=colors.PowerNorm(gamma=0.25))
sc.set_xlabel('$g_{elpd}$')
sc.set_ylabel('$g_{var}$')
fig = plt.gcf()

cax = fig.get_axes()[1]
cax.set_ylabel('$\sqrt{\kappa}$')

# we can change it by setting hover to True
cursor = mplcursors.cursor(sc, hover=True)# by default the annotation displays the xy positions
# this is to change it to the countries name
@cursor.connect("add")
def on_add(sel):
    arm_name = exp_data_df.loc[sel.target.index, 'arm_name']
    kappa = exp_data_df.loc[sel.target.index, 'kappa']
    kappa_sqrt = exp_data_df.loc[sel.target.index, 'kappa_sqrt']
    num_states = exp_data_df.loc[sel.target.index, 'num_states']
    text = f'Arm: {arm_name}\nKappa: {kappa}\nKappa_sqrt: {kappa_sqrt}\nNum_states: {num_states}'
    sel.annotation.set(text=text)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [ ]:
plt.savefig('../.out/illustrations/pareto.pdf')

In [ ]:
selected_data = exp_data_df[exp_data_df['gap_elpd'] >=500]
selected_data

Empty DataFrame
Columns: [gap_elpd, gap_pos_tr_val_elpd, arm_name_x, kappa, num_states, arm_name_y, gap_pos_tr_val_elpd_mean, gap_pos_tr_val_elpd_sem, arm_name, gap_elpd_mean, gap_elpd_sem, kappa_sqrt]
Index: []

In [ ]:
import matplotlib
# selected_data = exp_data_df[exp_data_df['num_states'] >=9]
sc = selected_data.plot.scatter('gap_elpd', 'gap_pos_tr_val_elpd', c='kappa_sqrt', cmap=my_cmap)

# we can change it by setting hover to True
cursor = mplcursors.cursor(sc, hover=True)# by default the annotation displays the xy positions
# this is to change it to the countries name
@cursor.connect("add")
def on_add(sel):
    arm_name = selected_data.loc[sel.target.index, 'arm_name']
    gap_pos_tr_val_elpd = selected_data.loc[sel.target.index, 'gap_pos_tr_val_elpd']
    kappa = selected_data.loc[sel.target.index, 'kappa']
    kappa_sqrt = selected_data.loc[sel.target.index, 'kappa_sqrt']
    num_states = selected_data.loc[sel.target.index, 'num_states']
    text = f'Arm: {arm_name}\ng_var: {gap_pos_tr_val_elpd}\nKappa: {kappa}\nkappa_sqrt: {kappa_sqrt}\nNum_states: {num_states}'
    sel.annotation.set(text=text)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …